version: '3'

services:
  nifi:
    image: apache/nifi:1.23.2
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - ./output:/output

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=cppl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cppl654321
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
  
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=cppl654321
      - MYSQL_DATABASE=cppl2
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=cppl654321
    ports:
      - "3306:3306"
    volumes:
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
